### ISSUE TITLE
Arc clippy issue

### ISSUE THREAD

**Issue by angel1st** [figengungor/clippy_flutter#5]
Hi there,
First of all - thanks for this excellent flutter package. I have a possible issue / question:
I want to have an `Arc`, on top of the widget and this is basically the code I use to make it:

````
@override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    return Padding(
      padding: const EdgeInsets.only(top: 8.0),
      child: Arc(
        height: 50,
        clipShadows: [ClipShadow(color: Colors.black)],
        edge: Edge.TOP,
        arcType: ArcType.CONVEX,
        child: Container(
          width: width * 0.62,
          child: Card(
            child: Column(
              children: <Widget>[
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    SizedBox(width: width * 0.6, child: WeightScaleWidget()),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
}
````

and the result is:

![Screenshot_1567696611](https://user-images.githubusercontent.com/8547131/64356087-f3338100-d00a-11e9-9747-e918845886b7.png)

as you can see the arc peak has one unnecessary shadow (between two red lines), which actually makes the arc to look not exactly as an arc. 

If however, `arcType: ArcType.CONVEY`, the arc looks as it should. See below:

![Screenshot_1567697514](https://user-images.githubusercontent.com/8547131/64356466-984e5980-d00b-11e9-86b2-1d0e48e00249.png)

**Comment by figengungor** [comment]
Hi @angel1st,
Good to hear that you found it excellent and you're welcome.

The issue is Card has a default margin and that causes that look. If you set margin to zero, it'll be fixed.

```
Card(margin:  EdgeInsets.zero,...)
```

**Comment by angel1st** [comment]
Thanks, @figengungor, your suggestion fixes the issue. I am closing the issue.
